# Copyright 2026 Bytedance Ltd. and/or its affiliates
# Licensed under the Apache License, Version 2.0

"""Durable collection windows for preempt-safe Group-Relative FPO.

One window contains candidate groups generated by exactly one frozen policy
version. Collectors may run on unrelated nodes and at unrelated times. A group
becomes visible only after its directory is atomically committed.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import os
import secrets
import shutil
import time
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterator

from verl import DataProto

SCHEMA_VERSION = 1


def _atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}-{time.time_ns()}")
    try:
        temporary.write_text(
            json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"Expected a JSON object in {path}.")
    return value


def abandon_owner_leases(window_dir: str | Path, owner_id: str) -> list[str]:
    """Release all candidate leases held by a collector known to be dead.

    The caller must have authoritative lifecycle evidence (for example, Slurm
    reports the task missing, or the watcher has cancelled it after a fatal
    renderer error). Atomic commit still validates the random lease token, so
    a late stale process cannot publish after this release.
    """

    if not owner_id:
        raise ValueError("owner_id must be non-empty.")
    window = Path(window_dir).expanduser().resolve()
    leases_dir = window / "leases"
    lock_path = window / ".window.lock"
    if not window.is_dir() or not lock_path.exists():
        raise FileNotFoundError(f"Collection window is not initialized: {window}")

    released: list[str] = []
    with lock_path.open("a+", encoding="utf-8") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        try:
            for lease_path in sorted(leases_dir.glob("candidate_*.json")):
                current = _read_json(lease_path)
                if current.get("owner_id") != owner_id:
                    continue
                candidate_id = str(current.get("assignment", {}).get("candidate_id") or lease_path.stem)
                lease_path.unlink(missing_ok=True)
                released.append(candidate_id)
                event = {
                    "event": "abandon",
                    "candidate_id": candidate_id,
                    "owner_id": owner_id,
                    "token": current.get("token"),
                    "at_unix_s": time.time(),
                }
                with (window / "LEASE_EVENTS.jsonl").open("a", encoding="utf-8") as stream:
                    stream.write(json.dumps(event, sort_keys=True) + "\n")
        finally:
            fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
    return released


def skip_window_candidates(
    window_dir: str | Path,
    candidate_ids: list[str],
    *,
    reason: str,
) -> list[str]:
    """Mark explicitly cancelled proposals without fabricating rollout data."""

    if not candidate_ids or not reason:
        raise ValueError("candidate_ids and reason must be non-empty.")
    window = Path(window_dir).expanduser().resolve()
    manifest = _read_json(window / "manifest.json")
    maximum = int(manifest["max_candidate_groups"])
    normalized: list[str] = []
    for candidate_id in candidate_ids:
        prefix = "candidate_"
        if not candidate_id.startswith(prefix) or not candidate_id[len(prefix) :].isdigit():
            raise ValueError(f"Invalid candidate id: {candidate_id}")
        index = int(candidate_id[len(prefix) :])
        if not 0 <= index < maximum:
            raise ValueError(f"Candidate index outside [0,{maximum}): {candidate_id}")
        normalized.append(f"candidate_{index:04d}")
    if len(normalized) != len(set(normalized)):
        raise ValueError("candidate_ids must be unique.")

    skipped_dir = window / "skipped"
    skipped_dir.mkdir(exist_ok=True)
    released: list[str] = []
    with (window / ".window.lock").open("a+", encoding="utf-8") as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        try:
            if (window / "CLOSED.json").exists() or not (window / "OPEN").exists():
                raise RuntimeError(f"Collection window is closed: {window}")
            for candidate_id in normalized:
                accepted = window / "accepted" / candidate_id / "COMMITTED"
                rejected = window / "rejected" / f"{candidate_id}.json"
                skipped = skipped_dir / f"{candidate_id}.json"
                if accepted.exists() or rejected.exists() or skipped.exists():
                    continue
                _atomic_write_json(
                    skipped,
                    {
                        "schema_version": SCHEMA_VERSION,
                        "candidate_id": candidate_id,
                        "reason": reason,
                        "skipped_at_unix_s": time.time(),
                    },
                )
                (window / "leases" / f"{candidate_id}.json").unlink(missing_ok=True)
                released.append(candidate_id)
        finally:
            fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
    return released


@dataclass(frozen=True)
class PolicyIdentity:
    """Identity that all candidates in one on-policy window must share."""

    immutable_base_path: str
    immutable_base_sha256: str
    trainer_checkpoint_path: str | None
    rollout_policy_version: int


@dataclass(frozen=True)
class CollectionWindowSpec:
    run_id: str
    intended_update: int
    group_size: int
    target_accepted_groups: int
    minimum_accepted_groups: int
    max_candidate_groups: int
    policy: PolicyIdentity
    complete_round_after_target: bool = False
    candidate_round_size: int = 0
    drain_candidate_budget: bool = False
    task_names: tuple[str, ...] = ()
    suite_ids: tuple[int, ...] = ()
    condition_manifest_sha256: str = ""
    group_reward_source: str = "binary_success"
    informative_group_criterion: str = "full_success_mixed"
    accepted_group_reduction: str = "group_equal"
    policy_seed_namespace: str = ""
    raw_state_abs_limit: float = 100.0
    # Collection is method-agnostic except for the behavior-policy trace that
    # must be persisted with every action chunk.  FPO reconstructs its CFM
    # statistics during training; Flow-GRPO must record the stochastic SDE
    # transition trace at rollout time.
    actor_objective: str = "fpo"
    flow_grpo_noise_level: float = 0.01

    def __post_init__(self) -> None:
        if not self.run_id or "/" in self.run_id:
            raise ValueError("run_id must be a non-empty path component.")
        if self.intended_update <= 0:
            raise ValueError("intended_update must be positive.")
        if self.group_size != 8:
            raise ValueError("Fragmented GRFPO collection requires group_size=8.")
        if not 1 <= self.minimum_accepted_groups <= self.target_accepted_groups:
            raise ValueError("minimum_accepted_groups must be in [1,target_accepted_groups].")
        if self.max_candidate_groups < self.target_accepted_groups:
            raise ValueError("max_candidate_groups must be at least target_accepted_groups.")
        if self.complete_round_after_target and self.drain_candidate_budget:
            raise ValueError(
                "complete_round_after_target and drain_candidate_budget are mutually exclusive."
            )
        if self.complete_round_after_target:
            if self.candidate_round_size <= 0:
                raise ValueError("candidate_round_size must be positive in round-balanced mode.")
            if self.max_candidate_groups % self.candidate_round_size:
                raise ValueError(
                    "max_candidate_groups must contain only complete candidate rounds: "
                    f"{self.max_candidate_groups} % {self.candidate_round_size} != 0."
                )
        if self.group_reward_source not in {"binary_success", "process_score"}:
            raise ValueError(f"Unsupported group_reward_source={self.group_reward_source!r}.")
        if self.informative_group_criterion not in {
            "binary_success",
            "full_success_mixed",
            "reward_variance",
        }:
            raise ValueError(
                f"Unsupported informative_group_criterion={self.informative_group_criterion!r}."
            )
        if self.informative_group_criterion == "reward_variance" and self.group_reward_source != "process_score":
            raise ValueError("reward_variance collection requires process_score rewards.")
        if self.accepted_group_reduction not in {"group_equal", "task_equal"}:
            raise ValueError(
                "accepted_group_reduction must be 'group_equal' or 'task_equal', "
                f"got {self.accepted_group_reduction!r}."
            )
        if not 0 < self.raw_state_abs_limit < float("inf"):
            raise ValueError("raw_state_abs_limit must be finite and positive.")
        if self.actor_objective not in {"fpo", "flow_grpo"}:
            raise ValueError(
                "actor_objective must be 'fpo' or 'flow_grpo', "
                f"got {self.actor_objective!r}."
            )
        if not 0 < self.flow_grpo_noise_level < float("inf"):
            raise ValueError("flow_grpo_noise_level must be finite and positive.")

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["task_names"] = list(self.task_names)
        payload["suite_ids"] = list(self.suite_ids)
        return {"schema_version": SCHEMA_VERSION, **payload}


@dataclass(frozen=True)
class CandidateAssignment:
    candidate_index: int
    task_name: str
    task_id: int
    suite_id: int
    layout_id: int
    policy_seeds: tuple[int, ...]

    @property
    def candidate_id(self) -> str:
        return f"candidate_{self.candidate_index:04d}"


@dataclass(frozen=True)
class CandidateLease:
    """Exclusive, expiring ownership of one not-yet-committed candidate."""

    assignment: CandidateAssignment
    owner_id: str
    token: str
    claimed_at_unix_s: float
    heartbeat_at_unix_s: float
    expires_at_unix_s: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SCHEMA_VERSION,
            "assignment": asdict(self.assignment),
            "owner_id": self.owner_id,
            "token": self.token,
            "claimed_at_unix_s": self.claimed_at_unix_s,
            "heartbeat_at_unix_s": self.heartbeat_at_unix_s,
            "expires_at_unix_s": self.expires_at_unix_s,
        }


def candidate_assignment(
    *,
    spec: CollectionWindowSpec,
    candidate_index: int,
    task_names: list[str],
    suite_ids: list[int],
    training_layouts: dict[tuple[str, int], list[int]],
    run_seed: int,
) -> CandidateAssignment:
    """Return a reproducible, outcome-independent candidate assignment."""

    if not 0 <= candidate_index < spec.max_candidate_groups:
        raise ValueError(f"candidate_index must be in [0,{spec.max_candidate_groups}), got {candidate_index}.")
    if not task_names:
        raise ValueError("task_names must not be empty.")
    if not suite_ids or len(set(suite_ids)) != len(suite_ids):
        raise ValueError("suite_ids must contain at least one unique RoboDojo suite id.")
    condition_count = len(task_names) * len(suite_ids)
    condition_slot = candidate_index % condition_count
    task_slot, suite_slot = divmod(condition_slot, len(suite_ids))
    task_name = task_names[task_slot]
    suite_id = int(suite_ids[suite_slot])
    layout_schedule = training_layouts.get((task_name, suite_id))
    if not layout_schedule or len(set(layout_schedule)) != len(layout_schedule):
        raise ValueError(
            "training_layouts must provide a non-empty unique layout pool for every "
            f"(task,suite); missing/invalid ({task_name!r},{suite_id})."
        )
    # Rotate independently within each fixed task/suite lane. The schedule is
    # declared before outcomes are observed, so filtering cannot cherry-pick a
    # layout after seeing its reward.
    condition_attempt = candidate_index // condition_count
    layout_slot = (
        condition_attempt * 7 + condition_slot * 11 + spec.intended_update - 1
    ) % len(layout_schedule)
    seed_namespace = spec.policy_seed_namespace or spec.run_id
    seed_payload = (
        f"{seed_namespace}:{run_seed}:{spec.policy.rollout_policy_version}:{spec.intended_update}:{candidate_index}"
    ).encode()
    seed_base = int.from_bytes(hashlib.sha256(seed_payload).digest()[:8], "big") % 2_000_000_000
    policy_seeds = tuple(seed_base + member for member in range(spec.group_size))
    return CandidateAssignment(
        candidate_index=candidate_index,
        task_name=task_name,
        task_id=task_slot,
        suite_id=suite_id,
        layout_id=int(layout_schedule[layout_slot]),
        policy_seeds=policy_seeds,
    )


class CollectionWindowStore:
    """Shared-filesystem transaction boundary for one frozen-theta window."""

    def __init__(self, root: str | Path, spec: CollectionWindowSpec) -> None:
        self.root = Path(root).expanduser().resolve()
        self.spec = spec
        self.window_dir = (
            self.root
            / spec.run_id
            / f"update_{spec.intended_update:04d}_theta_{spec.policy.rollout_policy_version:04d}"
        )
        self.accepted_dir = self.window_dir / "accepted"
        self.rejected_dir = self.window_dir / "rejected"
        self.skipped_dir = self.window_dir / "skipped"
        self.integrity_failures_dir = self.window_dir / "integrity_failures"
        self.leases_dir = self.window_dir / "leases"
        self.lock_path = self.window_dir / ".window.lock"

    @contextmanager
    def _locked(self) -> Iterator[None]:
        self.window_dir.mkdir(parents=True, exist_ok=True)
        with self.lock_path.open("a+", encoding="utf-8") as lock:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(lock.fileno(), fcntl.LOCK_UN)

    def initialize(self) -> None:
        """Create the window or verify an existing window is identical."""

        with self._locked():
            manifest_path = self.window_dir / "manifest.json"
            expected = self.spec.to_dict()
            if manifest_path.exists():
                actual = _read_json(manifest_path)
                # Schema-1 windows created before round-balanced closing used
                # immediate target closing.  Preserve that interpretation when
                # such a window is resumed by newer code.
                normalized_actual = dict(actual)
                normalized_actual.setdefault("complete_round_after_target", False)
                normalized_actual.setdefault("candidate_round_size", 0)
                normalized_actual.setdefault("drain_candidate_budget", False)
                # Legacy windows did not persist their candidate schedule.
                # They remain resumable, while every newly created window pins
                # the selected tasks/suites and condition-manifest identity.
                normalized_actual.setdefault("task_names", expected["task_names"])
                normalized_actual.setdefault("suite_ids", expected["suite_ids"])
                normalized_actual.setdefault(
                    "condition_manifest_sha256", expected["condition_manifest_sha256"]
                )
                normalized_actual.setdefault("group_reward_source", "binary_success")
                normalized_actual.setdefault("informative_group_criterion", "full_success_mixed")
                normalized_actual.setdefault("accepted_group_reduction", "group_equal")
                normalized_actual.setdefault("policy_seed_namespace", "")
                normalized_actual.setdefault("raw_state_abs_limit", 100.0)
                normalized_actual.setdefault("actor_objective", "fpo")
                normalized_actual.setdefault("flow_grpo_noise_level", 0.01)
                if normalized_actual != expected:
                    raise RuntimeError(
                        f"Collection window manifest mismatch at {manifest_path}: expected={expected}, stored={actual}."
                    )
            else:
                _atomic_write_json(manifest_path, expected)
                (self.window_dir / "OPEN").touch()
            self.accepted_dir.mkdir(exist_ok=True)
            self.rejected_dir.mkdir(exist_ok=True)
            self.skipped_dir.mkdir(exist_ok=True)
            self.integrity_failures_dir.mkdir(exist_ok=True)
            self.leases_dir.mkdir(exist_ok=True)

    def record_integrity_failure(
        self,
        *,
        assignment: CandidateAssignment,
        diagnostics: dict[str, Any],
        lease: CandidateLease | None = None,
    ) -> Path | None:
        """Record a retriable bad rollout without consuming its candidate id."""

        now = time.time()
        with self._locked():
            if lease is not None and not self._lease_is_current_locked(lease):
                return None
            self.integrity_failures_dir.mkdir(exist_ok=True)
            path = self.integrity_failures_dir / (
                f"{assignment.candidate_id}_attempt_{time.time_ns()}_{os.getpid()}.json"
            )
            _atomic_write_json(
                path,
                {
                    "schema_version": SCHEMA_VERSION,
                    "candidate": asdict(assignment),
                    "policy": asdict(self.spec.policy),
                    "diagnostics": diagnostics,
                    "owner_id": lease.owner_id if lease is not None else None,
                    "failed_at_unix_s": now,
                    "retriable": True,
                },
            )
            with (self.window_dir / "LEASE_EVENTS.jsonl").open("a", encoding="utf-8") as stream:
                stream.write(
                    json.dumps(
                        {
                            "event": "integrity_failure",
                            "candidate_id": assignment.candidate_id,
                            "candidate_index": assignment.candidate_index,
                            "owner_id": lease.owner_id if lease is not None else None,
                            "at_unix_s": now,
                            "raw_state_absmax": diagnostics.get("raw_state_absmax"),
                            "nonfinite_count": diagnostics.get("nonfinite_count"),
                        },
                        sort_keys=True,
                    )
                    + "\n"
                )
            return path

    def _verify_open_locked(self) -> None:
        if (self.window_dir / "CLOSED.json").exists() or not (self.window_dir / "OPEN").exists():
            raise RuntimeError(f"Collection window is closed: {self.window_dir}")

    def candidate_complete(self, candidate_id: str) -> bool:
        return (self.accepted_dir / candidate_id / "COMMITTED").is_file() or (
            self.rejected_dir / f"{candidate_id}.json"
        ).is_file() or (self.skipped_dir / f"{candidate_id}.json").is_file()

    def _lease_path(self, candidate_id: str) -> Path:
        return self.leases_dir / f"{candidate_id}.json"

    def claim_candidate(
        self,
        *,
        assignments: list[CandidateAssignment],
        owner_id: str,
        lease_timeout_seconds: float,
        preferred_condition: tuple[str, int] | None = None,
    ) -> CandidateLease | None:
        """Atomically claim one unfinished candidate from the shared queue.

        A condition preference is used by a warm persistent simulator. Passing
        ``None`` enables cross-condition stealing after that simulator exits.
        Expired leases are reclaimable, so preemption loses at most the group
        that had not yet reached the durable commit boundary.
        """

        if not owner_id:
            raise ValueError("owner_id must be non-empty.")
        if lease_timeout_seconds <= 0:
            raise ValueError("lease_timeout_seconds must be positive.")
        candidate_ids = [assignment.candidate_id for assignment in assignments]
        if len(candidate_ids) != len(set(candidate_ids)):
            raise ValueError("assignments must contain unique candidate ids.")
        if preferred_condition is not None:
            assignments = [
                assignment
                for assignment in assignments
                if (assignment.task_name, assignment.suite_id) == preferred_condition
            ]

        with self._locked():
            if (self.window_dir / "CLOSED.json").exists():
                return None
            self._verify_open_locked()
            now = time.time()
            for assignment in sorted(assignments, key=lambda item: item.candidate_index):
                candidate_id = assignment.candidate_id
                if not self.round_ready_to_start(assignment.candidate_index):
                    continue
                if self.candidate_complete(candidate_id):
                    self._lease_path(candidate_id).unlink(missing_ok=True)
                    continue
                lease_path = self._lease_path(candidate_id)
                reclaimed = False
                if lease_path.exists():
                    current = _read_json(lease_path)
                    # A Slurm --requeue or the local Isaac crash supervisor
                    # restarts the Python child only after its predecessor is
                    # gone. The stable array-job/task owner may therefore
                    # reacquire immediately instead of waiting for expiry.
                    same_owner_restart = current["owner_id"] == owner_id
                    if not same_owner_restart and float(current["expires_at_unix_s"]) > now:
                        continue
                    reclaimed = True
                lease = CandidateLease(
                    assignment=assignment,
                    owner_id=owner_id,
                    token=secrets.token_hex(16),
                    claimed_at_unix_s=now,
                    heartbeat_at_unix_s=now,
                    expires_at_unix_s=now + lease_timeout_seconds,
                )
                _atomic_write_json(lease_path, lease.to_dict())
                event = {
                    "event": "reclaim" if reclaimed else "claim",
                    "candidate_id": candidate_id,
                    "candidate_index": assignment.candidate_index,
                    "owner_id": owner_id,
                    "suite_id": assignment.suite_id,
                    "task_name": assignment.task_name,
                    "token": lease.token,
                    "at_unix_s": now,
                }
                with (self.window_dir / "LEASE_EVENTS.jsonl").open("a", encoding="utf-8") as stream:
                    stream.write(json.dumps(event, sort_keys=True) + "\n")
                return lease
        return None

    def renew_candidate_lease(self, lease: CandidateLease, *, lease_timeout_seconds: float) -> CandidateLease:
        """Extend a live lease, rejecting a stale worker after reassignment."""

        if lease_timeout_seconds <= 0:
            raise ValueError("lease_timeout_seconds must be positive.")
        with self._locked():
            lease_path = self._lease_path(lease.assignment.candidate_id)
            if not lease_path.exists():
                raise RuntimeError(f"Candidate lease no longer exists: {lease.assignment.candidate_id}")
            current = _read_json(lease_path)
            if current["token"] != lease.token or current["owner_id"] != lease.owner_id:
                raise RuntimeError(f"Candidate lease ownership changed: {lease.assignment.candidate_id}")
            now = time.time()
            renewed = CandidateLease(
                assignment=lease.assignment,
                owner_id=lease.owner_id,
                token=lease.token,
                claimed_at_unix_s=lease.claimed_at_unix_s,
                heartbeat_at_unix_s=now,
                expires_at_unix_s=now + lease_timeout_seconds,
            )
            _atomic_write_json(lease_path, renewed.to_dict())
            return renewed

    def release_candidate_lease(self, lease: CandidateLease) -> bool:
        """Release a lease after a recoverable local failure."""

        with self._locked():
            lease_path = self._lease_path(lease.assignment.candidate_id)
            if not lease_path.exists():
                return False
            current = _read_json(lease_path)
            if current["token"] != lease.token or current["owner_id"] != lease.owner_id:
                return False
            lease_path.unlink()
            return True

    def _lease_is_current_locked(self, lease: CandidateLease) -> bool:
        lease_path = self._lease_path(lease.assignment.candidate_id)
        if not lease_path.exists():
            return False
        current = _read_json(lease_path)
        return current["token"] == lease.token and current["owner_id"] == lease.owner_id

    def round_ready_to_start(self, candidate_index: int) -> bool:
        """Allow a candidate only after every lane in the prior round committed.

        This barrier prevents faster task/suite lanes from entering an extra
        round while a slower lane is still finishing the round that crossed the
        accepted-group target.
        """

        if not self.spec.complete_round_after_target:
            return True
        round_start = (candidate_index // self.spec.candidate_round_size) * self.spec.candidate_round_size
        return all(self.candidate_complete(f"candidate_{index:04d}") for index in range(round_start))

    def commit_group(
        self,
        *,
        assignment: CandidateAssignment,
        rollout: DataProto,
        rollout_end_obs: DataProto,
        group_record: dict[str, Any],
        lease: CandidateLease | None = None,
    ) -> str:
        """Atomically publish an accepted group, or a compact rejection record.

        Returns ``accepted``, ``rejected``, ``duplicate``, ``late``, or
        ``stale_lease``.
        """

        candidate_id = assignment.candidate_id
        if len(rollout) != self.spec.group_size or len(rollout_end_obs) != self.spec.group_size:
            raise ValueError(
                f"{candidate_id} must contain exactly G={self.spec.group_size} trajectories: "
                f"rollout={len(rollout)}, end_obs={len(rollout_end_obs)}."
            )
        if int(group_record["rollout_policy_version"]) != self.spec.policy.rollout_policy_version:
            raise ValueError("Candidate rollout policy version does not match its collection window.")
        if str(group_record["group_id"]) != candidate_id:
            raise ValueError("group_record.group_id must equal the deterministic candidate id.")

        informative = bool(group_record["informative"])
        tmp_dir: Path | None = None
        if informative:
            tmp_dir = self.window_dir / f".{candidate_id}.tmp-{os.getpid()}-{time.time_ns()}"
            tmp_dir.mkdir()
            try:
                rollout.save_to_disk(tmp_dir / "rollout.pkl")
                rollout_end_obs.save_to_disk(tmp_dir / "rollout_end_obs.pkl")
                metadata = {
                    "schema_version": SCHEMA_VERSION,
                    "candidate": asdict(assignment),
                    "policy": asdict(self.spec.policy),
                    "group_record": group_record,
                }
                _atomic_write_json(tmp_dir / "metadata.json", metadata)
                (tmp_dir / "COMMITTED").touch()
            except BaseException:
                shutil.rmtree(tmp_dir, ignore_errors=True)
                raise

        with self._locked():
            if lease is not None:
                if lease.assignment != assignment:
                    if tmp_dir is not None:
                        shutil.rmtree(tmp_dir, ignore_errors=True)
                    raise ValueError("Lease assignment does not match the committed candidate.")
                if not self._lease_is_current_locked(lease):
                    if tmp_dir is not None:
                        shutil.rmtree(tmp_dir, ignore_errors=True)
                    return "stale_lease"
            if self.candidate_complete(candidate_id):
                if tmp_dir is not None:
                    shutil.rmtree(tmp_dir, ignore_errors=True)
                return "duplicate"
            if (self.window_dir / "CLOSED.json").exists():
                if tmp_dir is not None:
                    shutil.rmtree(tmp_dir, ignore_errors=True)
                return "late"
            self._verify_open_locked()
            if informative:
                assert tmp_dir is not None
                os.replace(tmp_dir, self.accepted_dir / candidate_id)
                self._lease_path(candidate_id).unlink(missing_ok=True)
                return "accepted"
            _atomic_write_json(
                self.rejected_dir / f"{candidate_id}.json",
                {
                    "schema_version": SCHEMA_VERSION,
                    "candidate": asdict(assignment),
                    "policy": asdict(self.spec.policy),
                    "group_record": group_record,
                },
            )
            self._lease_path(candidate_id).unlink(missing_ok=True)
            return "rejected"

    def scan(self) -> dict[str, Any]:
        accepted = sorted(path for path in self.accepted_dir.glob("candidate_*") if (path / "COMMITTED").is_file())
        rejected = sorted(self.rejected_dir.glob("candidate_*.json"))
        skipped = sorted(self.skipped_dir.glob("candidate_*.json"))
        return {
            "accepted": accepted,
            "rejected": rejected,
            "skipped": skipped,
            "completed_candidate_count": len(accepted) + len(rejected) + len(skipped),
            "closed": (self.window_dir / "CLOSED.json").is_file(),
        }

    def close_if_ready(self) -> dict[str, Any] | None:
        """Close at target, optionally only after a complete balanced round."""

        with self._locked():
            existing = self.window_dir / "CLOSED.json"
            if existing.exists():
                return _read_json(existing)
            state = self.scan()
            accepted_count = len(state["accepted"])
            budget_exhausted = state["completed_candidate_count"] >= self.spec.max_candidate_groups
            if self.spec.drain_candidate_budget:
                # Transitional/diagnostic mode: retain M as the minimum target,
                # but consume the complete predeclared candidate budget and use
                # every informative group.  This avoids both target truncation
                # and pretending the accepted-group target equals the raw
                # candidate budget.
                if not budget_exhausted:
                    return None
            elif self.spec.complete_round_after_target:
                completed_ids = {
                    int(path.name.removeprefix("candidate_")) for path in state["accepted"]
                } | {
                    int(path.stem.removeprefix("candidate_")) for path in state["rejected"]
                } | {
                    int(path.stem.removeprefix("candidate_")) for path in state["skipped"]
                }
                completed_round = bool(completed_ids) and len(completed_ids) % self.spec.candidate_round_size == 0
                if completed_round:
                    completed_round = completed_ids == set(range(len(completed_ids)))
                if not completed_round:
                    return None
                if accepted_count < self.spec.target_accepted_groups and not budget_exhausted:
                    return None
            elif accepted_count < self.spec.target_accepted_groups and not budget_exhausted:
                return None
            if accepted_count < self.spec.minimum_accepted_groups:
                outcome = "insufficient_informative_groups"
                selected: list[Path] = []
            else:
                outcome = "ready"
                selected = (
                    state["accepted"]
                    if self.spec.complete_round_after_target or self.spec.drain_candidate_budget
                    else state["accepted"][: self.spec.target_accepted_groups]
                )
            payload = {
                "schema_version": SCHEMA_VERSION,
                "outcome": outcome,
                "accepted_groups": accepted_count,
                "rejected_groups": len(state["rejected"]),
                "skipped_candidate_groups": len(state["skipped"]),
                "completed_candidate_groups": state["completed_candidate_count"],
                "complete_round_after_target": self.spec.complete_round_after_target,
                "candidate_round_size": self.spec.candidate_round_size,
                "drain_candidate_budget": self.spec.drain_candidate_budget,
                "selected_group_paths": [str(path) for path in selected],
                "closed_at_unix_s": time.time(),
            }
            _atomic_write_json(existing, payload)
            (self.window_dir / "OPEN").unlink(missing_ok=True)
            return payload

    def load_selected_groups(self) -> list[tuple[DataProto, DataProto, dict[str, Any]]]:
        closed = _read_json(self.window_dir / "CLOSED.json")
        if closed["outcome"] != "ready":
            raise RuntimeError(f"Collection window is not trainable: {closed['outcome']}.")
        groups = []
        for path_text in closed["selected_group_paths"]:
            group_dir = Path(path_text).resolve()
            if self.accepted_dir != group_dir.parent or not (group_dir / "COMMITTED").is_file():
                raise RuntimeError(f"Selected group is outside this committed window: {group_dir}")
            metadata = _read_json(group_dir / "metadata.json")
            if metadata["policy"] != asdict(self.spec.policy):
                raise RuntimeError(f"Selected group has a different theta_old identity: {group_dir}")
            rollout = DataProto.load_from_disk(group_dir / "rollout.pkl")
            end_obs = DataProto.load_from_disk(group_dir / "rollout_end_obs.pkl")
            if len(rollout) != self.spec.group_size or len(end_obs) != self.spec.group_size:
                raise RuntimeError(f"Committed group has invalid G at {group_dir}.")
            groups.append((rollout, end_obs, metadata["group_record"]))
        return groups

    @contextmanager
    def training_transaction(
        self,
        receipt_path: str | Path | None = None,
    ) -> Iterator[dict[str, Any] | None]:
        """Serialize train-only retries while allowing process-death recovery.

        ``flock`` is released by the kernel when a preempted trainer exits. The
        yielded value is an existing receipt, or ``None`` when this caller must
        perform the update and write one before releasing the lock.
        """

        resolved_receipt = (
            self.window_dir / "TRAINED.json"
            if receipt_path is None
            else Path(receipt_path).expanduser().resolve()
        )
        resolved_receipt.parent.mkdir(parents=True, exist_ok=True)
        lock_path = (
            self.window_dir / ".training.lock"
            if receipt_path is None
            else resolved_receipt.with_name(f".{resolved_receipt.name}.lock")
        )
        with lock_path.open("a+", encoding="utf-8") as lock:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
            try:
                yield _read_json(resolved_receipt) if resolved_receipt.exists() else None
            finally:
                fcntl.flock(lock.fileno(), fcntl.LOCK_UN)

    def write_training_receipt(
        self,
        payload: dict[str, Any],
        receipt_path: str | Path | None = None,
    ) -> None:
        """Publish completion only after the new actor checkpoint is durable."""

        resolved_receipt = (
            self.window_dir / "TRAINED.json"
            if receipt_path is None
            else Path(receipt_path).expanduser().resolve()
        )
        if resolved_receipt.exists():
            raise FileExistsError(f"Training receipt already exists: {resolved_receipt}")
        _atomic_write_json(resolved_receipt, {"schema_version": SCHEMA_VERSION, **payload})
